export const baseNodes = [
    {
        type: 'input',
        category: 'input',
        name: 'Text Input',
        description: 'Accepts text input from the user',
        icon: 'Type',
        inputs: [
            {
                key: 'placeholder',
                label: 'Placeholder',
                type: 'string',
                placeholder: 'Enter text...',
                value: 'Enter text...',
            },
            {
                key: 'label',
                label: 'Label',
                type: 'string',
                placeholder: 'Input Label',
                value: 'Input Label',
            },
            { key: 'required', label: 'Required', type: 'boolean', value: false },
        ],
        outputs: [{ key: 'value', label: 'Value', type: 'string' }],
        meta: { validation: false },
    },
    {
        type: 'output',
        category: 'output',
        name: 'Text Output',
        description: 'Displays text output to the user',
        icon: 'TextCursorInput',
        inputs: [
            {
                key: 'text',
                label: 'Text',
                type: 'string',
                placeholder: 'Output text',
                value: 'Output text',
            },
            {
                key: 'format',
                label: 'Format',
                type: 'select',
                options: ['Plain', 'Markdown', 'HTML'],
                value: 'Plain',
            },
        ],
        outputs: [],
        meta: { styling: true },
    },
    {
        type: 'action',
        category: 'processing',
        name: 'API Call',
        description: 'Executes an HTTP API request',
        icon: 'Globe',
        inputs: [
            {
                key: 'url',
                label: 'URL',
                type: 'string',
                placeholder: 'https://api.example.com',
                value: 'https://api.example.com',
            },
            {
                key: 'method',
                label: 'Method',
                type: 'select',
                options: ['GET', 'POST', 'PUT', 'DELETE'],
                value: 'GET',
            },
            {
                key: 'headers',
                label: 'Headers',
                type: 'object',
                placeholder: 'Authorization: Bearer token',
                value: { Authorization: 'Bearer token' },
            },
            {
                key: 'body',
                label: 'Body',
                type: 'object',
                placeholder: "{ message: 'Hello' }",
                value: {},
            },
        ],
        outputs: [
            { key: 'response', label: 'Response', type: 'object' },
            { key: 'status', label: 'Status Code', type: 'number' },
        ],
        meta: { apiKey: false, env: false },
    },
    {
        type: 'condition',
        category: 'processing',
        name: 'If / Else',
        id: 'if_else',
        description: 'Binary logic router — routes flow on True or False',
        icon: 'Split',
        inputs: [],
        outputs: [],
        meta: { advanced: false },
    },
    {
        type: 'condition',
        category: 'processing',
        name: 'Intent Router',
        id: 'intent_router',
        description: 'Multi-branch router — routes flow based on detected intent or matched case',
        icon: 'GitBranchPlus',
        inputs: [],
        outputs: [],
        meta: { advanced: false },
    },
    {
        id: 'text_processor',
        type: 'processing',
        category: 'processing',
        name: 'AI Text Analyzer',
        description: 'Analyzes text using AI (Gemini, GPT, etc.) for general-purpose understanding.',
        icon: 'Bot',
        inputs: [
            {
                key: 'text',
                label: 'Input Text',
                type: 'string',
                placeholder: 'Text to process',
                value: '',
            },
        ],
        outputs: [
            { key: 'result', label: 'Analysis', type: 'object' },
            { key: 'intent', label: 'Intent', type: 'string' },
            { key: 'message', label: 'Direct Reply', type: 'string' },
            { key: 'tokenUsage', label: 'Token Usage', type: 'object' },
        ],
        meta: { apiKey: true, streaming: true },
    },
    {
        id: 'financial_processor',
        name: 'Financial Processor',
        description: 'AI processor specialized for Web3 transactions, balance checks, and financial analysis.',
        type: 'processing',
        category: 'processing',
        icon: 'Wallet',
        inputs: [
            {
                key: 'text',
                label: 'Financial Inquiry',
                type: 'string',
                placeholder: 'e.g. "Transfer 100 CKB"',
                value: '',
            },
        ],
        outputs: [
            { key: 'intent', label: 'Transaction Type', type: 'string' },
            { key: 'amount', label: 'Amount', type: 'number' },
            { key: 'address', label: 'Target Address', type: 'string' },
            { key: 'message', label: 'Confirmation Message', type: 'string' },
            { key: 'result', label: 'Full Extraction', type: 'object' },
        ],
        meta: { apiKey: true, streaming: true },
    },
    {
        id: 'social_processor',
        name: 'Social Processor',
        description: 'AI processor for social interaction, community engagement, and tone consistency.',
        type: 'processing',
        category: 'processing',
        icon: 'MessageSquare',
        inputs: [
            {
                key: 'text',
                label: 'User Input',
                type: 'string',
                placeholder: 'e.g. "What do you think of this NFT?"',
                value: '',
            },
        ],
        outputs: [
            { key: 'intent', label: 'Engagement Type', type: 'string' },
            { key: 'tone', label: 'Detected Tone', type: 'string' },
            { key: 'message', label: 'Draft Response', type: 'string' },
            { key: 'result', label: 'Full Analysis', type: 'object' },
        ],
        meta: { apiKey: true, streaming: true },
    },
    {
        id: 'operational_processor',
        name: 'Operational Processor',
        description: 'AI processor for task coordination, scheduling, and system monitoring.',
        type: 'processing',
        category: 'processing',
        icon: 'Settings',
        inputs: [
            {
                key: 'text',
                label: 'Action Task',
                type: 'string',
                placeholder: 'e.g. "Schedule a backup for midnight"',
                value: '',
            },
        ],
        outputs: [
            { key: 'task', label: 'Parsed Task', type: 'string' },
            { key: 'schedule', label: 'Detected Time', type: 'string' },
            { key: 'message', label: 'Acknowledgement', type: 'string' },
            { key: 'result', label: 'Execution Plan', type: 'object' },
        ],
        meta: { apiKey: true, streaming: true },
    },
    {
        type: 'processing',
        category: 'processing',
        name: 'Data Transformer',
        description: 'Transforms and reshapes data between nodes',
        icon: 'FileJson',
        inputs: [
            { key: 'data', label: 'Input Data', type: 'object', placeholder: '{}', value: {} },
            {
                key: 'transformation',
                label: 'Transformation',
                type: 'string',
                placeholder: 'data.map(item => item.value)',
                value: 'data.map(item => item.value)',
            },
        ],
        outputs: [{ key: 'result', label: 'Transformed Data', type: 'object' }],
        meta: { sandbox: true },
    },
];
