export const baseNodes = [
    {
        type: 'action',
        category: 'processing',
        name: 'API Call',
        description: 'Executes an API request',
        icon: 'Globe',
        inputs: [
            {
                key: 'url',
                label: 'URL',
                type: 'string',
                placeholder: 'https://api.example.com',
                value: 'https://api.example.com',
            },
            {
                key: 'headers',
                label: 'Headers',
                type: 'object',
                placeholder: 'Authorization: Bearer token',
                value: { Authorization: 'Bearer token' },
            },
            {
                key: 'body',
                label: 'Body',
                type: 'object',
                placeholder: "{ message: 'Hello, AI!' }",
                value: { message: 'Hello, AI!' },
            },
            {
                key: 'method',
                label: 'Method',
                type: 'select',
                options: ['GET', 'POST', 'PUT', 'DELETE'],
                value: 'GET',
            },
        ],
        outputs: [
            { key: 'response', label: 'Response', type: 'object' },
            { key: 'status', label: 'Status Code', type: 'number' },
        ],
        meta: { apiKey: true, env: false },
    },
    {
        type: 'input',
        category: 'input',
        name: 'Text Input',
        description: 'Accepts text input from the user',
        icon: 'Type',
        inputs: [
            {
                key: 'placeholder',
                label: 'Placeholder',
                type: 'string',
                placeholder: 'Enter text...',
                value: 'Enter text...',
            },
            {
                key: 'label',
                label: 'Label',
                type: 'string',
                placeholder: 'Input Label',
                value: 'Input Label',
            },
            { key: 'required', label: 'Required', type: 'boolean', value: false },
        ],
        outputs: [{ key: 'value', label: 'Value', type: 'string' }],
        meta: { validation: false },
    },
    {
        type: 'output',
        category: 'output',
        name: 'Text Output',
        description: 'Displays text output to the user',
        icon: 'TextCursorInput',
        inputs: [
            {
                key: 'text',
                label: 'Text',
                type: 'string',
                placeholder: 'Output text',
                value: 'Output text',
            },
            {
                key: 'format',
                label: 'Format',
                type: 'select',
                options: ['Plain', 'Markdown', 'HTML'],
                value: 'Plain',
            },
        ],
        outputs: [],
        meta: { styling: true },
    },
    {
        type: 'condition',
        category: 'condition',
        name: 'If/Else',
        id: 'if_else',
        description: 'Simple binary logic router (True/False)',
        icon: 'Split',
        inputs: [],
        outputs: [],
        meta: { advanced: false },
    },
    {
        type: 'condition',
        category: 'condition',
        name: 'Intent Router',
        id: 'intent_router',
        description: 'Multi-branch logic router for different intents or cases',
        icon: 'GitBranchPlus',
        inputs: [],
        outputs: [],
        meta: { advanced: false },
    },
    {
        id: 'text_processor',
        type: 'processing',
        category: 'processors',
        name: 'AI Text Analyzer',
        description: 'Analyzes text using AI models (Gemini, GPT, etc.) for general purpose understanding.',
        icon: 'Bot',
        inputs: [
            {
                key: 'text',
                label: 'Input Text',
                type: 'string',
                placeholder: 'Text to process',
                value: '',
            },
        ],
        outputs: [
            { key: 'result', label: 'Analysis', type: 'object' },
            { key: 'intent', label: 'Intent', type: 'string' },
            { key: 'message', label: 'Direct Reply', type: 'string' },
            { key: 'tokenUsage', label: 'Token Usage', type: 'object' },
        ],
        meta: { apiKey: true, streaming: true },
    },
    {
        id: 'financial_processor',
        name: 'Financial Processor',
        description: 'AI processor specialized for Web3 transactions, balance checks, and financial analysis.',
        type: 'processing',
        category: 'processors',
        icon: 'Wallet', // Added icon
        inputs: [
            {
                key: 'text',
                label: 'Financial Inquiry',
                type: 'string',
                placeholder: 'e.g. "Transfer 100 CKB"',
                value: '',
            },
        ],
        outputs: [
            { key: 'intent', label: 'Transaction Type', type: 'string' },
            { key: 'amount', label: 'Amount', type: 'number' },
            { key: 'address', label: 'Target Address', type: 'string' },
            { key: 'message', label: 'Confirmation Message', type: 'string' },
            { key: 'result', label: 'Full Extraction', type: 'object' },
        ],
        meta: { apiKey: true, streaming: true }, // Added meta
    },
    {
        id: 'social_processor',
        name: 'Social Processor',
        description: 'AI processor specialized for social interaction, community engagement, and tone consistency.',
        type: 'processing',
        category: 'processors',
        icon: 'MessageSquare', // Added icon
        inputs: [
            {
                key: 'text',
                label: 'User Input',
                type: 'string',
                placeholder: 'e.g. "What do you think of this NFT?"',
                value: '',
            },
        ],
        outputs: [
            { key: 'intent', label: 'Engagement Type', type: 'string' },
            { key: 'tone', label: 'Detected Tone', type: 'string' },
            { key: 'message', label: 'Draft Response', type: 'string' },
            { key: 'result', label: 'Full Analysis', type: 'object' },
        ],
        meta: { apiKey: true, streaming: true }, // Added meta
    },
    {
        id: 'operational_processor',
        name: 'Operational Processor',
        description: 'AI processor specialized for task coordination, scheduling, and system monitoring.',
        type: 'processing',
        category: 'processors',
        icon: 'Settings', // Added icon
        inputs: [
            {
                key: 'text',
                label: 'Action Task',
                type: 'string',
                placeholder: 'e.g. "Schedule a backup for midnight"',
                value: '',
            },
        ],
        outputs: [
            { key: 'task', label: 'Parsed Task', type: 'string' },
            { key: 'schedule', label: 'Detected Time', type: 'string' },
            { key: 'message', label: 'Acknowledgement', type: 'string' },
            { key: 'result', label: 'Execution Plan', type: 'object' },
        ],
        meta: { apiKey: true, streaming: true }, // Added meta
    },
    {
        type: 'input',
        category: 'input',
        name: 'File Upload',
        description: 'Accepts file uploads from the user',
        icon: 'FileUp',
        inputs: [
            {
                key: 'accept',
                label: 'Accepted Types',
                type: 'string',
                placeholder: '.pdf,.docx,image/*',
                value: '.pdf,.docx,image/*',
            },
            { key: 'maxSize', label: 'Max Size (MB)', type: 'number', placeholder: '5', value: 5 },
        ],
        outputs: [
            { key: 'file', label: 'File', type: 'object' },
            { key: 'content', label: 'Content', type: 'string' },
        ],
        meta: { multiple: false },
    },
    {
        type: 'processing',
        category: 'processing',
        name: 'Data Transformer',
        description: 'Transforms data from one format to another',
        icon: 'FileJson',
        inputs: [
            { key: 'data', label: 'Input Data', type: 'object', placeholder: '{}', value: {} },
            {
                key: 'transformation',
                label: 'Transformation',
                type: 'string',
                placeholder: 'data.map(item => item.value)',
                value: 'data.map(item => item.value)',
            },
        ],
        outputs: [{ key: 'result', label: 'Transformed Data', type: 'object' }],
        meta: { sandbox: true },
    },
    {
        type: 'output',
        category: 'output',
        name: 'Chart Output',
        description: 'Displays data as a chart',
        icon: 'BarChart',
        inputs: [
            { key: 'data', label: 'Chart Data', type: 'object', placeholder: '[]', value: [] },
            {
                key: 'type',
                label: 'Chart Type',
                type: 'select',
                options: ['Bar', 'Line', 'Pie', 'Scatter'],
                value: 'Bar',
            },
            {
                key: 'title',
                label: 'Chart Title',
                type: 'string',
                placeholder: 'Chart Title',
                value: 'Chart Title',
            },
        ],
        outputs: [],
        meta: { interactive: true },
    },
    {
        type: 'condition',
        category: 'condition',
        name: 'Switch Case',
        description: 'Routes based on multiple conditions',
        icon: 'SwitchCamera',
        inputs: [
            {
                key: 'value',
                label: 'Input Value',
                type: 'string',
                placeholder: 'Value to evaluate',
                value: '',
            },
            {
                key: 'cases',
                label: 'Cases',
                type: 'object',
                placeholder: "{case1: 'value1', case2: 'value2'}",
                value: { case1: 'value1', case2: 'value2' },
            },
        ],
        outputs: [
            { key: 'case1', label: 'Case 1', type: 'boolean' },
            { key: 'case2', label: 'Case 2', type: 'boolean' },
            { key: 'default', label: 'Default', type: 'boolean' },
        ],
        meta: { dynamic: true },
    },
    {
        type: 'input',
        category: 'input',
        name: 'Webhook Trigger',
        description: 'Triggers flow on webhook call',
        icon: 'Webhook',
        inputs: [
            {
                key: 'endpoint',
                label: 'Endpoint',
                type: 'string',
                placeholder: '/api/webhook',
                value: '/api/webhook',
            },
            { key: 'method', label: 'Method', type: 'select', options: ['GET', 'POST'], value: 'POST' },
        ],
        outputs: [
            { key: 'payload', label: 'Payload', type: 'object' },
            { key: 'headers', label: 'Headers', type: 'object' },
        ],
        meta: { authentication: false },
    },
];
