export const cryptoNodes = [
    {
        type: 'crypto_wallet',
        category: 'processing',
        name: 'Crypto Wallet',
        description: 'Connect to a cryptocurrency wallet',
        icon: 'Wallet',
        inputs: [
            {
                key: 'connectionType',
                label: 'Connection Type',
                type: 'select',
                options: ['Private Key', 'Wallet Address', 'MetaMask'],
                value: 'Wallet Address',
            },
            {
                key: 'walletAddress',
                label: 'Wallet Address',
                type: 'string',
                placeholder: '0x...',
                value: '',
            },
            {
                key: 'privateKey',
                label: 'Private Key',
                type: 'string',
                placeholder: 'Only if using Private Key connection',
                value: '',
            },
            {
                key: 'network',
                label: 'Network',
                type: 'select',
                options: ['Ethereum', 'CKB', 'Binance Smart Chain', 'Polygon', 'Solana'],
                value: 'Ethereum',
            },
        ],
        outputs: [
            { key: 'walletInfo', label: 'Wallet Info', type: 'object' },
            { key: 'balance', label: 'Balance', type: 'number' },
            { key: 'connected', label: 'Connected', type: 'boolean' },
        ],
        meta: { secure: true },
    },
    {
        type: 'crypto_trade',
        category: 'processing',
        name: 'Crypto Trade',
        description: 'Execute cryptocurrency trades',
        icon: 'TrendingUp',
        inputs: [
            {
                key: 'walletInfo',
                label: 'Wallet Info',
                type: 'object',
                placeholder: 'Connect to Crypto Wallet node first',
                value: null,
            },
            {
                key: 'action',
                label: 'Action',
                type: 'select',
                options: ['Buy', 'Sell', 'Swap'],
                value: 'Buy',
            },
            {
                key: 'token',
                label: 'Token',
                type: 'string',
                placeholder: 'ETH, BTC, SOL, etc.',
                value: 'ETH',
            },
            {
                key: 'amount',
                label: 'Amount',
                type: 'number',
                placeholder: '1.0',
                value: 0.1,
            },
            {
                key: 'targetToken',
                label: 'Target Token (for Swap)',
                type: 'string',
                placeholder: 'USDT, USDC, etc.',
                value: 'USDT',
            },
            {
                key: 'priceLimit',
                label: 'Price Limit',
                type: 'number',
                placeholder: '0 for market price',
                value: 0,
            },
        ],
        outputs: [
            { key: 'transactionId', label: 'Transaction ID', type: 'string' },
            { key: 'status', label: 'Status', type: 'string' },
            { key: 'details', label: 'Transaction Details', type: 'object' },
        ],
        meta: { secure: true },
    },
    {
        type: 'trading_bot',
        category: 'processing',
        name: 'Trading Bot',
        description: 'AI-powered trading bot for crypto',
        icon: 'BrainCircuit',
        inputs: [
            {
                key: 'walletInfo',
                label: 'Wallet Info',
                type: 'object',
                placeholder: 'Connect to Crypto Wallet node first',
                value: null,
            },
            {
                key: 'strategy',
                label: 'Trading Strategy',
                type: 'select',
                options: ['Conservative', 'Balanced', 'Aggressive', 'Custom'],
                value: 'Balanced',
            },
            {
                key: 'tokens',
                label: 'Tokens to Trade',
                type: 'object',
                placeholder: '["ETH", "BTC", "SOL"]',
                value: ['ETH', 'BTC'],
            },
            {
                key: 'budget',
                label: 'Trading Budget',
                type: 'number',
                placeholder: 'Maximum amount to trade',
                value: 1000,
            },
            {
                key: 'timeframe',
                label: 'Analysis Timeframe',
                type: 'select',
                options: ['1h', '4h', '1d', '1w'],
                value: '4h',
            },
            {
                key: 'customRules',
                label: 'Custom Trading Rules',
                type: 'string',
                placeholder: 'Enter custom trading logic',
                value: '',
            },
        ],
        outputs: [
            { key: 'recommendation', label: 'Trading Recommendation', type: 'object' },
            { key: 'analysis', label: 'Market Analysis', type: 'object' },
            { key: 'performance', label: 'Bot Performance', type: 'object' },
        ],
        meta: { aiPowered: true, secure: true },
    },
];
